# Generated by Django 4.0.3 on 2022-03-07 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_movie', models.CharField(max_length=100, verbose_name='Fav Glick')),
                ('favorite_editor', models.CharField(blank=True, choices=[('vim', 'Vim'), ('emacs', 'Emacs'), ('np', 'NotePad'), ('cat', 'cat > filename')], max_length=5, verbose_name='Favorite Editor')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
